components/Footer.vue
components/Video.vue
components/ui/Button_switch.vue
components/ui/Video_frame.vue
layouts/default.vue
pages/index.vue

Добавил компонент Video, Button-switch, Video_iframe и создал секцию Video

feat: Добавить компонент Video с вложенными компонентами

---

components/story.vue
pages/story.vue

Создала статью-историю

---

components/Cover.vue
components/Cover_about.vue
components/ui/Button_down.vue
components/Без названия.code-workspace
pages/index.vue

первоначальная версия cover и cover-about

первая версия блоков cover и cover-about

---

components/Footer.vue
components/Header.vue
components/Popup.vue
components/ui/Menu.vue

Добавил эффекты при наведении ссылкам и кнопкам, убрал баги формы

Dev share form

---

components/Video.vue
components/ui/Button_switch.vue
components/ui/Video_frame.vue

Сделал кнопки в блоке Видео активными

feat: Оживить блок Video

---

components/Popup.vue
components/Video.vue
layouts/default.vue

Добавил рабочие кнопки на 768px, выход из попапа по ESC, видео больше не перекрывает попап.

feat: Закрытие попап по клику

---

components/Cover.vue
components/Cover_about.vue

адаптив cover и cover-about включая 768px

адаптив cover и cover-about включая 768px

---

components/Cover.vue
components/Story_input.vue

исправил блок cover, добавил адаптив для input-search

исправил блок cover, добавил адаптив для input-search

---

components/Popup.vue

fix: Исправить переменную

---

components/Footer.vue
components/Header.vue
components/Story_input.vue
components/Video.vue

style: Исправить стили на больших разрешениях

---

components/Cover.vue
components/Video.vue

сделал кнопку в блоке cover рабочей, внес соответствующие изменения в медиа запросах блока video

сделал кнопку в блоке cover рабочей, внес соответствующие изменения в медиа запросах блока video

---

store/index.js

Создал раздел store, чтобы он был у всех и можно было обрабатывать данные через него

feat: создать раздел store

---

components/story.vue

Сделала адаптив для блока story на всех разрешениях. После слияния ветку наверное лучше удалить. И ветку dev-article наверное стоит удалить, чтобы дальше уже в новой ветке можно было работать со всеми изменениями, а эти не копить.

Сделать адаптив для блока story

---

components/Footer.vue
components/Header.vue
nuxt.config.js
plugins/route.js
static/images/hider-open.svg
static/images/hider.svg
store/header-menu.js

Добавил полный адаптив блока Header, и работающее меню

style: Добавить полный адаптив блоку Header

---

components/Cover.vue
components/Cover_about.vue

сделал адптив блока cover исправил все ошибки по этому блоку

сделал адптив блока cover исправил все ошибки по этому блоку

---

components/Cover_about.vue

исправил ошибки по ревью в этом блоке

cover-about адаптив до 320

---

components/ui/input.vue

fix: Исправить имена переменных

---

components/Cover_about.vue
components/Story_input.vue
components/ui/Button_search.vue

исправил ошибки по ревью сделал адаптив

исправил ошибки по ревью сделал адаптив

---

components/story.vue

Внести правки

---

components/ui/CardStory.vue

Reverts Lsnsky/project_raklechitsa#54

Revert "style поправить название класса"

---

components/Cover_about.vue
components/Story_input.vue

- кнопка больше не прыгает при смене текста
- добавил подчеркивания на маленьких разрешениях  
- поправил стили

доработал блоки cover-about и story-input 

---

components/StoriesAll.vue

отключить calcItemPerPage в storiesAll

refactor: отключить calcItemPerPage в storiesAll

---

components/Pagination.vue
components/Stories.vue
components/StoriesAll.vue
components/story.vue
store/storiesData.js

feat: сделать пагинацию

---

components/StoriesAll.vue

Добавил работающий поиск на странице с историями

feat: Добавить работающий поиск

---

components/Cover.vue
components/Video.vue

feat: Добавить плавный скролл

---

components/Cover.vue
components/Header.vue
components/Pagination.vue
components/Photos.vue
components/Stories.vue
components/Video.vue

Переписал логику пагинации и скрола

refactor: Преписать логику пагинации и скрола

---

components/Photos.vue
components/ui/CardStatContent.vue
components/ui/CardStatSource.vue
components/ui/CardStatTitle.vue
components/ui/CardStory.vue
components/ui/Diagram.vue
components/ui/ProgressBar.vue
components/ui/Social_icon.vue
components/ui/Video_frame.vue

refactor:поправить разметку, раскрыть пропсы

refactor:поправить разметку, раскрыть пропсы

---

components/Photos.vue
components/Story_input.vue

- поправить стили в блоке инстаграм

Dev fix: поправить стили в блоке инстаграм

---

components/ui/Button_down.vue
components/ui/Button_history.vue
components/ui/CardStatContent.vue
components/ui/CardStatSource.vue
components/ui/CardStatTitle.vue
components/ui/Photo.vue
components/ui/Video_frame.vue

поправить нейминг классов по БЭМ

style:поправить нейминг классов по БЭМ

---

components/Statistics.vue
store/statisticsData.js

отрисовать двойные графики статистики по макету

refactor:отрисовать двойные графики статистики по макету

---

layouts/error.vue

feat: title для 404

---

components/Cover_about.vue

Dev fix: поправить паддинг

---

components/StoriesAll.vue

добавить блок с пустым поиском

feat:добавить блок с пустым поиском

---

components/BottomCards.vue
components/Callback.vue
components/CardContainer.vue
components/Cover_about.vue
components/Footer.vue
components/Header.vue
components/Photos.vue
components/Questionnaire.vue
components/Statistics.vue
components/Stories.vue
components/StoriesAll.vue
components/Story_input.vue
components/Video.vue
components/story.vue
components/ui/Button_history.vue
components/ui/CardStory.vue
components/ui/Diagram.vue
components/ui/Menu.vue
components/ui/Panel.vue
components/ui/ProgressBar.vue

Удалила все дублирующиеся стили. По результату полазила по сайту. Вроде все работает ровненько.

Dev article Правки стилей

---

components/Callback.vue
components/Questionnaire.vue
layouts/default.vue
pages/index.vue
store/callback.js
store/questionnaire.js

Добавить post запросы, изменить получение данных инстаграма

feat: Добавить post запросы, изменить получение данных инстаграма

---

components/Story_input.vue

fix: добавил нужный padding 

---

components/Callback.vue

fix: кнопка отправить

---

components/Cover.vue
components/Cover_about.vue

feat: добавил кнопки в cover и cover-about

---

components/BottomCards.vue
components/Stories.vue
components/StoriesAll.vue
store/storiesData.js

Добавил карточки селебрити наверх, теперь на основной странице они не могут зарандомиться, а на страницах с отдельной историей могут

feat: Добавить селебрити стори

---

components/Cover.vue

feat: пульсирующая кнопка

---

components/Cover_about.vue
components/Header.vue
components/Story_input.vue
components/ui/Button.vue

пофиксил хедер в продакшене, добавил ховеры

feat: Ховеры кнопок

---

components/Video.vue
components/ui/Button_switch.vue
static/images/button-swith_purple.svg

feat: добавить ховеры в Video

---

components/Callback.vue
components/Questionnaire.vue

fix: Чистка опросников

---

components/Cover.vue
components/Story_input.vue

исправил немного кнопку в cover, убрал лишние стили в story-input

fix: поправил кнопку

---

components/Cover.vue
components/Story_input.vue

сделал остановку анимации при наведении на кнопку

fix: финальный вариант кнопки

---

components/BottomCards.vue
components/Callback.vue
components/Questionnaire.vue
components/Stories.vue
components/StoriesAll.vue
components/Video.vue
components/story.vue
components/ui/Button_history.vue
components/ui/Button_switch.vue
components/ui/CardStatTitle.vue
components/ui/Policy_text.vue
store/storiesData.js

fix: Замечания ревью

---

components/Cover_about.vue
components/Story_input.vue

fix: исправил названия классов по БЭМ
